### PR TITLE
Student5 feature6-7&8

### PR DESCRIPTION
**Pull request by elguille2**
Se han implementado las funcionalidades 6 ,7 y 8 del Student 5.

6 Operations by auditors on code audits #161  :
• List the code audits that they have created.
• Show the details of their code audits.
• Create, update, or delete their code audits. Code audits can be updated or deleted as long as they have not been published. For a code audit to be published, the mark must be, at least, “C”.

7 Operations by auditors on audit records #162  :
• List the audit records in their code audits.
• Show the details of their audit records.
• Create and publish an audit record.
• Update or delete an audit record as long as it is not published.

8 Operations by auditors on auditor dashboards #163 :

- Show their auditor dashboards.

### CODE REVIEW

**Comment by alvcarber1** [comment]
Con respecto al requisito 7:

Al crear un nuevo Audit Record, introduzco el siguiente formato de fecha -> 2021-05-17 19:00
Dicho formato me lleva a un error 500.
image

Cuando muestro los detalles de un Audit Record, el campo de Mark no aparece como un desplegable, hay que introducir los datos a mano, por lo que no se que notas son aceptadas por el sistema:
image

**Comment by alvcarber1** [comment]
Con respecto al requisito 8:
Los datos se muestran correctamente.

**Comment by Gabrielvcg** [comment]
Exceptuando las correcciones que muy habílmente ha ejecutado el compañero, lo veo bien.

**Comment by alvcarber1** [comment]
Todo funciona correctamente. Errores corregidos. Buen trabajo 👍

**Pull request merged**
